---
# Needed to install gnupg
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600

# gnupg gpg command is needed to download parsoid package key
# apt-transport-https is needed to run apt-get update later
- name: install gnupg and apt-transport-https
  apt: name={{item}}
  with_items:
  - gnupg
  - apt-transport-https

- name: add jenkins key to apt-key
  apt_key: file=/root/jenkins.io.key

- name: jenkins sources.list
  template: >
    src=jenkins.io.list.j2
    dest=/etc/apt/sources.list.d/jenkins.io.list
    force=no
  register: sources_list_result

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
