---
- name: add jenkins key to apt-key
  apt_key: file=/root/jenkins.io.key
  sudo: yes

- name: jenkins sources.list
  template: >
    src=jenkins.io.list.j2
    dest=/etc/apt/sources.list.d/jenkins.io.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
